website:
  container_name: metamask_website
  build: ./
  restart: always
  ports:
    - "8080"
  environment:
    VIRTUAL_PORT: "8080"
    VIRTUAL_HOST: "metamask.io"
    LETSENCRYPT_HOST: "metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"
